In [1]:
import numpy as np
print(np.__version__)

1.21.5


ZERO dimensional array

In [2]:
import numpy as np

arr=np.array(46)
print(arr)

46


1 D array

In [3]:
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


2D array

In [4]:

arr=np.array([[1,2],[4,5]])
print(arr)

[[1 2]
 [4 5]]


3D Array

In [5]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


All Dimensions

In [6]:
print(np.array(10))  #0D
print(np.array([1,2])) #1D
print(np.array([[1,2],[3,4]]))  #2D
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])) #3d

10
[1 2]
[[1 2]
 [3 4]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=4)
print(arr)

[[[[ 1  2  3  4  5  6  7  8  9 10]]]]


In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=4)
print(arr.ndim)

4


shape is the number of elements in the array

In [9]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


you can easily create an array filled with 0's or any number

In [18]:
import numpy as np
arr1=np.zeros(10)  #for 1D
arr2=np.zeros((2,4)) #for 2D
arr3=np.zeros((3,1,5))  #for 3D
print(arr1)
print(arr2)
print(arr3)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]]]


In [11]:
arr=np.ones((50,50))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [12]:
arr=np.arange(9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [13]:
arr=np.arange(17,170,17)
print(arr)

[ 17  34  51  68  85 102 119 136 153]


Sorting

In [14]:
import numpy as np
arr=np.array([5,4,6,7,8,9,1,2,3,10])
print(np.sort(arr))


[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
import numpy as np
arr=np.array(['Priyanka','Supriya','Kiran','Akash','Vinaya','Harish','Huligemma'])
print(np.sort(arr))

['Akash' 'Harish' 'Huligemma' 'Kiran' 'Priyanka' 'Supriya' 'Vinaya']


Sorting an 2D array

In [24]:
import numpy as np
arr=np.array([[12,10,11],[6,8,7]])
print(np.sort(arr))

[[10 11 12]
 [ 6  7  8]]


In [25]:
import numpy as np
arr=np.array([['z','x','a'],['s','p','r']])
print(np.sort(arr))

[['a' 'x' 'z']
 ['p' 'r' 's']]


In [46]:
arr=np.array([10,200,30,400,500,600,70,800])
print(arr[3:5])

[400 500]


In [51]:
mat=np.array([[10,20],[30,40]])
print(mat[0,0])
print(mat[0,1])
print(mat[1,0])
print(mat[1,1])

10
20
30
40


In [56]:
mat=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(mat)
print(mat[1,4])

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
100


In [69]:
mat=np.array([[[10,2,30,45,12],[80,59,46,34,90]],[[11,51,21,89,98],[6,7,8,9,0]]])
print(mat)
print(mat[1,1,0])

[[[10  2 30 45 12]
  [80 59 46 34 90]]

 [[11 51 21 89 98]
  [ 6  7  8  9  0]]]
6


In [74]:
mat=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(mat)
print(mat[0,0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [77]:
arr=np.array([1,2,3,4,5,6])
print(arr[1:6:2])

[2 4 6]


In [87]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])

[6 7 8]


In [90]:
arr=np.array([1,2,3,40,40,50,40])
x=np.where(arr==40)
print(x)

(array([3, 4, 6], dtype=int64),)


In [88]:
arr=np.array([1,2,3,4,5])
x=np.where(arr%2==0)
print(x)

(array([1, 3], dtype=int64),)


In [91]:

x=np.searchsorted([1,2,4,5,6],3)
print(x)

2


In [94]:
arr=np.array([1,2,3,4,5,6,7,8,9])
x=arr.reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [95]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
x=arr.reshape(2,6)
print(x)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


numpy filter

In [2]:
import numpy as np
arr=np.array([10,30,40,50,100,90])
b=[True,False,True,False,True,False]
newarr=arr[b]
print(newarr)

[ 10  40 100]


In [11]:
import numpy as np
arr=np.array([1,3,5,6,2,8,10])
result=filter(lambda x: x % 2!=0,arr)
print(list(result))

[1, 3, 5]


In [12]:
import numpy as np
arr=np.array([1,3,5,6,2,8,10])
result=filter(lambda x: x % 2==0,arr)
print(list(result))

[6, 2, 8, 10]


Concatenation

In [22]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,13).reshape(2,3)
print("B:",b)

con=np.concatenate((a,b))
print("CON:",con)

d=np.arange(14,20).reshape(2,3)
print("D :",d)

mat=np.concatenate((con,d))
print("mat:",mat)


A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]]
CON: [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
D : [[14 15 16]
 [17 18 19]]
mat: [[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]
 [14 15 16]
 [17 18 19]]


In [28]:
mat1=np.concatenate((a,b),axis=1)
print(mat1)

[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


In [38]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(7,13).reshape(2,3)
print("B:",b)

stack_mat=np.stack((a,b),axis=-1)
print("Stack:",stack_mat)

A: [[0 1 2]
 [3 4 5]]
B: [[ 7  8  9]
 [10 11 12]]
Stack: [[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [44]:
v_stack=np.vstack((a,b))   #Verticle Stack
v_stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
h_stack=np.hstack((a,b))         #Horizontal Stack
h_stack

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [53]:
d_stack=np.dstack((a,b))
d_stack

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

In [54]:
mat=np.dstack((a,b))
print(mat[1,1,1])
print(mat)

11
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [55]:
v_stack=np.vstack((a,b,con))   #Verticle Stack
v_stack

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

PANDAS

In [65]:
import pandas as pd

x=np.array([10,20,30,40,40])
S=pd.Series(x)
S


0    10
1    20
2    30
3    40
4    40
dtype: int32

In [66]:
import pandas as pd 
x=np.array(['S','U','P','R','I','Y','A'])
s=pd.Series(x,index=['a','b','c','d','e','f','g'])
s

a    S
b    U
c    P
d    R
e    I
f    Y
g    A
dtype: object

In [78]:
import pandas as pd
x=np.array(['S','U','P','R','I','Y','A'])
s=pd.Series(x,index=['a','b','c','d','e','f','g'])
print(x['e'])

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices