In [7]:
import array as ar
arr=ar.array("i",[1,2,3,4,5])
print(arr[3])

4


In [3]:
#1D Array--It has one row and multiple columns

#2D Array--It has Multiple rows and multiple columns

#We can not access diectly 2D[Multidimensional array] so we use third party package that is numpy

#For using numpy we have install numpy by using "pip install numpy"

from numpy import *
arr=array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#we have 6 ways to create an array those are[array()],[linspace()],[logspace()],[arange()],[zeros()],[ones()]

#array()
from numpy import *
arr=array([1,2,3,4,5],float)
print(arr)

#converting int into float
arr=array([1,2,3,4,5],float)
print(arr.dtype)
print(arr)

[1. 2. 3. 4. 5.]
float64
[1. 2. 3. 4. 5.]


In [27]:
#linspace()
from numpy import *
arr=linspace(1,9,3) #nuber start with one end with 9 then 1 to 9 digits are  equaly divided by 3 
print(arr)

[1. 5. 9.]


In [22]:
#arange()
arr=arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [13]:
#logspace() 
arr=logspace(1,40,3)
print(arr)

[1.00000000e+01 3.16227766e+20 1.00000000e+40]


In [30]:
#zeros()
arr=zeros([4,4],int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [32]:
#ones()
arr=ones([3,4],float)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
#Adding two arrys it is also called as "vectorized operation"
arr1=array([1,2,3,4,5])
arr2=arr1+5
print(arr2)

arr3=array([8,5,3,1,9])
arr4=array([2,4,6,8,10])
arr5=arr3+arr4
print(arr5)

[ 6  7  8  9 10]
[10  9  9  9 19]


In [33]:
arr=array([1,144,9,6,18,144])
print(sin(arr))
print(cos(arr))
print(log(arr))
print(sqrt(arr))
print(min(arr))
print(max(arr))
print(sort(arr))
print(unique(arr))


#Concatinations of two arrays
arr1=array([1,2,3,4])
arr2=array([5,6,7,8])
print(concatenate([arr1,arr2]))

[ 0.84147098 -0.49102159  0.41211849 -0.2794155  -0.75098725 -0.49102159]
[ 0.54030231  0.8711474  -0.91113026  0.96017029  0.66031671  0.8711474 ]
[0.         4.9698133  2.19722458 1.79175947 2.89037176 4.9698133 ]
[ 1.         12.          3.          2.44948974  4.24264069 12.        ]
1
144
[  1   6   9  18 144 144]
[  1   6   9  18 144]
[1 2 3 4 5 6 7 8]


In [35]:
#copy an array
arr1=array([1,2,3,4,5])
arr2=arr1
print(arr1)
print(arr2)

print(id(arr1))#here we are creating a new aliasing for the array
print(id(arr2))


arr1=array([1,2,3,4,5])
arr2=arr1.view() #function which will help u to create new array of the different location
print(arr1)
print(arr2)


[1 2 3 4 5]
[1 2 3 4 5]
2284334776656
2284334776656
[1 2 3 4 5]
[1 2 3 4 5]


In [36]:
#we have two different types of copy [Shallow Copy]  [Deep Copy]

#Shallow Copy
arr1=array([5,6,7,8,9])
arr1=arr2.view()

arr1[1]=7
print(arr1)
print(arr2)

[1 7 3 4 5]
[1 7 3 4 5]


In [37]:
#Deepcopy
arr1=array([5,6,7,8,9])
arr1=arr2.copy()
arr1[2]=10
print(arr1)
print(arr2)

[ 1  7 10  4  5]
[1 7 3 4 5]


Working with matrix

In [35]:
from numpy import *

arr=array([
    [1,2,3],
    [4,5,6]
])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)#it given rows and columns[in tuple]
print(arr.size)



#How to convert 2D array to 1D array
arr1=array([[1,2,3],[5,6,7]])
arr2=arr1.flatten()
print(arr2)


#converting single dimensional to multi dimensional
arr1=array([1,2,4,5])
arr3=arr1.reshape(2,2)
print(arr3)

arr1=array([[1,2,3,4,5,6],
            [3,2,1,4,5,6]])
print(arr1.reshape(3,4))
print(arr1.reshape(2,2,3))

int32
2
(2, 3)
6
[1 2 3 5 6 7]
[[1 2]
 [4 5]]
[[1 2 3 4]
 [5 6 3 2]
 [1 4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[3 2 1]
  [4 5 6]]]


In [36]:
from numpy import *

m=matrix("1 2 3 ; 4 5 6 ; 7 8 9")
print(m)
print(diagonal(m))
print(m.max())
print(m.min())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]
9
1


In [80]:
#Multipying Two Matrices
m1=matrix('1 2 3 ; 4 5 6; 7 8 9')
m2=matrix('9 8 7 ; 6 5 4 ; 3 2 1')
m3=m1*m2
print(m3)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


Functions

In [83]:
def greet():
    print("Hello")
    print("Hii")

greet()
greet()

Hello
Hii
Hello
Hii


In [87]:
#Addition of two numbers
def addition(a,b):
    c=a+b
    print(c) 
    

addition(2,3)

5


In [90]:
def squareroot_fun(x):
    return sqrt(x)

x=int(input("enter the number"))
result=squareroot_fun(x)
print(int(result))

12
